// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeismicEventsFireEvents.Data;

#nullable disable

namespace SeismicEventsFireEvents.Migrations
{
    [DbContext(typeof(SeismicEventsFireEventsDbContext))]
    [Migration("20251221210648_Init_SQLLite")]
    partial class Init_SQLLite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("SeismicEventsFireEvents.Models.SeismicCompressedProperties", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChunkId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("CompressedEventProperties")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("CompressionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EventCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FirstEventDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FlynnRegion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastEventDate")
                        .HasColumnType("TEXT");

                    b.Property<double?>("MaxDepth")
                        .HasColumnType("REAL")
                        .HasColumnName("MaximumDepth");

                    b.Property<double?>("MaxLatitude")
                        .HasColumnType("REAL")
                        .HasColumnName("MaximumLatitude");

                    b.Property<double?>("MaxLongitude")
                        .HasColumnType("REAL")
                        .HasColumnName("MaximumLongitude");

                    b.Property<double?>("MaxMagnitude")
                        .HasColumnType("REAL")
                        .HasColumnName("MaximumMagnitude");

                    b.Property<double?>("MinDepth")
                        .HasColumnType("REAL")
                        .HasColumnName("MinimumDepth");

                    b.Property<double?>("MinLatitude")
                        .HasColumnType("REAL")
                        .HasColumnName("MinimumLatitude");

                    b.Property<double?>("MinLongitude")
                        .HasColumnType("REAL")
                        .HasColumnName("MinimumLongitude");

                    b.Property<double?>("MinMagnitude")
                        .HasColumnType("REAL")
                        .HasColumnName("MinimumMagnitude");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SeismicCompressed");
                });

            modelBuilder.Entity("SeismicEventsFireEvents.Models.SeismicProperties", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Depth")
                        .HasColumnType("REAL");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlynnRegion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Magnitude")
                        .HasColumnType("REAL");

                    b.Property<string>("MagnitudeType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceCatalog")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Time")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SeismicProperties");
                });
#pragma warning restore 612, 618
        }
    }
}
