// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeismicEventsFireEvents.Data;

#nullable disable

namespace SeismicEventsFireEvents.Migrations
{
    [DbContext(typeof(SeismicEventsFireEventsDbContext))]
    [Migration("20251124224220_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SeismicEventsFireEvents.Models.SeismicCompressedProperties", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChunkId")
                        .HasColumnType("int");

                    b.Property<byte[]>("CompressedEventProperties")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("CompressionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FirstEventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FlynnRegion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastEventDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("MaxDepth")
                        .HasColumnType("float");

                    b.Property<double?>("MaxLatitude")
                        .HasColumnType("float");

                    b.Property<double?>("MaxLongitude")
                        .HasColumnType("float");

                    b.Property<double?>("MaxMagnitude")
                        .HasColumnType("float");

                    b.Property<double?>("MinDepth")
                        .HasColumnType("float");

                    b.Property<double?>("MinLatitude")
                        .HasColumnType("float");

                    b.Property<double?>("MinLongitude")
                        .HasColumnType("float");

                    b.Property<double?>("MinMagnitude")
                        .HasColumnType("float");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
